### ISSUE TITLE
it produces "^H" when I hit [backspace] on kmscon login phase

### ISSUE THREAD

**Issue by wind0204** [kmscon/kmscon#69]
"it produces "^H" when I hit [backspace] on kmscon login phase" instead of removing a character
in my gentoo box

**Comment by xtbqimuxmvtx** [comment]
Apologies for resurrecting this ancient thread, but I ran into a similiar issue on EndeavourOS (Arch-like; successor to Antergos) - I haven't well tested it, but this one came up in a (Brave) an internet search:

- Endeavour OS 6.12.1-arch1-1
- util-linux 2.40.2-1
- kmscon-patched-git (AUR)
- - 9.0.0.r20.g0f73dc3-1
- - Forked and patched version by https://github.com/Aetf/kmscon
- I couldn't find any information outside of the login.defs file, arch's documentation or anything, /etc/login.defs :
`#
# /etc/login.defs - Configuration control definitions for the shadow package.
#
#       $Id$
#
# NOTE: This file is adapted for the use on Arch Linux!
#       Unsupported options due to the use of util-linux or PAM are removed.

#
# Delay in seconds before being allowed another attempt after a login failure
# Note: When PAM is used, some modules may enforce a minimum delay (e.g.
#       pam_unix(8) enforces a 2s delay)
#
`

Things you should try before my patchfix: 
- Try the kmscon by dvdhrm or unpatched version (yay -Syu kmscon)
- Figure out what is actually overriding the variable:

My patchfix; added VERARE  binding to /etc/login.defs:

`#
# Set BackSpace to Erase in login prompt
#
VERASE                  \010`

**Comment by xtbqimuxmvtx** [comment]
UPDATE: Found some reference in man login.defs.5 ; perhaps the oldness of this thread has sent me down the wrong path:

https://man.archlinux.org/man/login.defs.5.en#BUGS

>

>  #[BUGS](https://man.archlinux.org/man/login.defs.5.en#BUGS)
> 
> Much of the functionality that used to be provided by the shadow password suite is now handled by PAM. Thus, /etc/login.defs is no longer used by [passwd(1)](https://man.archlinux.org/man/passwd.1.en), or less used by [login(1)](https://man.archlinux.org/man/login.1.en), and [su(1)](https://man.archlinux.org/man/su.1.en). Please refer to the corresponding PAM configuration files instead.
> #[SEE ALSO](https://man.archlinux.org/man/login.defs.5.en#SEE_ALSO)
> 
> [login(1)](https://man.archlinux.org/man/login.1.en), [shadow(5)](https://man.archlinux.org/man/shadow.5.en), [pam(8)](https://man.archlinux.org/man/pam.8.en).
